sudo: false
language: node_js
node_js:
  - '4'
  - '6'
  - '7'
script:
  - npm run lint
  - npm test
after_success:
  - npm run coveralls
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
notifications:
  email: false
